version: '3.9'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file: ./db/.env
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/workspace/api
    depends_on:
      - db

volumes:
  db-volume: